refactor(all) remove function prefix from all shell files
webinstall/webi-installers pull request #471
Opened 2022-08-15 04:39 UTC by brij-desaii

for issue #464

2022-08-15 08:57 UTC, y0rune commented
Hello!
I added the comments when you remove the word `function`.
The files with `.md` it should not been changed. I think you done a little bit more regex to remove it in the repo.

2022-08-15 09:05 UTC, y0rune requested changes

2022-08-15 09:05 UTC, y0rune commented on node/install.sh
> +# The custom s for node are here.
I think it should be restore the word `function` here ;)

2022-08-15 09:05 UTC, y0rune commented on node/install.sh
> +# The generic s - version checks, download, extract, etc - are here:
I think it should be restore the word `function` here ;)

2022-08-15 09:05 UTC, y0rune requested changes
Hello!
I added the comments when you remove the word `function`.
The files:
- `.md` 
- `jshint/jshintrc.defaults.json5`

it should not been changed. 

I think you done a little bit more regex to remove it in the repo.

2022-08-15 20:51 UTC, coolaj86 commented
@brij-desaii Do you want to try this again?

2022-08-16 05:03 UTC, brij-desaii commented
> 



>

2022-08-16 05:08 UTC, brij-desaii commented
Hey, @coolaj86! This is my first time contributing to an opensource project on github and I'm a bit confused 😅. As per my understanding, I have accidently removed the word "function" from the comments in the shell files and I'm not sure how to fix this mistake. Could you please help me out?

2022-08-16 07:32 UTC, coolaj86 commented
@brij-desaii
1. You can't just do a find-and-replace through _all_ of the files. You need to do it only to `.sh` files.
2. You need to use a tool that can pattern match `function (name)\(\)` and replace it with `$1()`. I believe I gave an example of that in the issue with [`sd`](https://webinstall.dev/sd).
3. To fix the git history you can:
  - `git reset main --hard` to undo your old commit
  - `git push --force` to push over your current PR

2022-08-18 04:51 UTC, closed without merging