Add --workdir flag to brew updater
webinstall/webi-installers pull request #701
Opened 2023-10-24 04:28 UTC by Virtual4087

Fixes #700

2023-10-24 05:38 UTC, coolaj86 commented
I will pull this in tomorrow.

2023-10-25 04:35 UTC, coolaj86 commented on brew/brew-update-service-install
> +        --workdir ~/.local/opt/brew/ \
this needs to move up one line

```diff
+        --workdir ~/.local/opt/brew/ \
          --name sh.brew.updater -- \
-        --workdir ~/.local/opt/brew/ \
```

2023-10-25 04:36 UTC, coolaj86 requested changes
this needs to move up one line

```diff
+        --workdir ~/.local/opt/brew/ \
          --name sh.brew.updater -- \
-        --workdir ~/.local/opt/brew/ \
```

2023-10-25 04:36 UTC, coolaj86 commented on brew/brew-update-service-install
> +        --workdir ~/.local/opt/brew/ \
this needs to move up one line

```diff
+        --workdir ~/.local/opt/brew/ \
          --name sh.brew.updater -- \
-        --workdir ~/.local/opt/brew/ \
```

The `--` means "don't accept flags after me"

2023-10-25 04:36 UTC, coolaj86 commented
I would have made that change myself, but you unchecked "allow maintainer commits" when making the PR.

2023-10-25 04:41 UTC, Virtual4087 commented
> I would have made that change myself, but you unchecked "allow maintainer commits" when making the PR.

my bad I didn't notice it, I'll make the changes right away

2023-10-25 04:49 UTC, coolaj86 commented
@Virtual4087 Now it's swapped around the other way. I updated my comment to hopefully be more clear.

2023-10-25 04:55 UTC, Virtual4087 commented
@coolaj86 can i open a new pr with a single commit and proper changes?

2023-10-25 05:07 UTC, coolaj86 commented
@Virtual4087 it's good to just learn how to use `git` rather than make a new PR.

```sh
# reset the branch back to the beginning
git reset --hard main
git pull --rebase https://github.com/webinstall/webi-installers main

# make your edits and commit
git commit -m "fix(brew): add --workdir to updater service"

# replace the feature branch
git push --force
```

2023-10-25 05:09 UTC, Virtual4087 commented
Ok I'm on it. Thanks for the explanation

2023-10-25 06:29 UTC, Virtual4087 reviewed
Thanks you @coolaj86. I learned something new today. This month has really taught me a lot about git.

2023-10-25 17:05 UTC, coolaj86 approved these changes
@Virtual4087 Thanks!

And I'm glad you were able to learn more about git. I wish more people would - because it's a great tool that solves so many problems that couldn't be solved ~15 years ago (before it went mainstream).

Also, apparently it was some bad settings on my end that were giving me an error that I assumed was you having unchecked the "allow maintainer edits" button.

2023-10-25 17:16 UTC, merged