feat: add rudimentry --list and --info flags
webinstall/webi-installers pull request #710
Opened 2023-10-25 19:52 UTC by coolaj86

```sh
webi --list
```

```text
[warn] the format of --list output may change

atomicparsley
awless
archiver
# ...
watchexec
zoxide
yq
```

```sh
webi --info ssh-pubkey
webi --info node
```

```text
'ssh-pubkey' is a special case that does not have releases
```

```json5
// Stable 'node' releases:
[
  {
    "name": "node-v20.9.0-aix-ppc64.tar.gz",
    "version": "20.9.0",
    "lts": true,
    "channel": "stable",
    "date": "2023-10-24",
    "os": "aix",
    "arch": "ppc64",
    "ext": "tar.gz",
    "download": "https://nodejs.org/download/release/v20.9.0/node-v20.9.0-aix-ppc64.tar.gz"
  }
]
```

2023-10-28 07:32 UTC, jojobyte approved these changes

2023-10-30 07:38 UTC, coolaj86 commented on _webi/template.sh
> +        if test -n "${WEBI_SINGLE}"; then
verified that `webi_install` isn't used externally and removed shellcheck comment

2023-10-30 07:39 UTC, coolaj86 commented on _webi/template.sh
> -        # TODO need to test that the above actually worked
It's been a few years. This has never popped up.

2023-10-30 07:41 UTC, coolaj86 commented on _webi/bootstrap.sh
> +        mktemp -d -t "webi-\$WEBI_TIMESTAMP.XXXXXXXX"
It seems that just putting this on its own line got rid of a linter warning.

That may mean that it's a false negative and the command should still be lifted later.

2023-10-30 07:42 UTC, coolaj86 commented on _webi/template.sh
> +        if test -z "${pkg_no_exec}"; then
this allows us to skip `xattr` no git cloned directories, which aren't handled properly by `xattr`.

2023-10-30 07:47 UTC, merged

2025-11-09 04:36 UTC, fidelmeramon-maker requested changes
- [ ] @